<a href="https://colab.research.google.com/github/Punam105/NUMPY/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print("1D Array:", a)

b = np.array([[1, 2], [3, 4],[10,12]])
print("2D Array:\n", b)


1D Array: [1 2 3]
2D Array:
 [[ 1  2]
 [ 3  4]
 [10 12]]


In [3]:
print("Shape:", b.shape)
print("Size:", b.size)
print("Datatype:", b.dtype)


Shape: (3, 2)
Size: 6
Datatype: int64


In [4]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
randoms = np.random.rand(2, 2)
randoms

array([[0.05208773, 0.32849322],
       [0.99244745, 0.3448071 ]])

In [7]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Addition:", x + y)
print("Multiplication:", x * y)
print("Dot Product:", np.dot(x, y))


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


In [9]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # First element
print(arr[1:4])    # Slice from index 1 to 3


10
[20 30 40]


In [10]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = np.array([[[1], [2]], [[3], [4]]])

print("1D:", a)
print("2D:\n", b)
print("3D:\n", c)


1D: [1 2 3]
2D:
 [[1 2]
 [3 4]]
3D:
 [[[1]
  [2]]

 [[3]
  [4]]]


In [11]:
np.random.randint(1, 10, (2, 3))

array([[2, 9, 1],
       [5, 1, 2]])

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Reshape to 3x2:\n", arr.reshape(3, 2))
print("Flatten:", arr.flatten())


Reshape to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Flatten: [1 2 3 4 5 6]


In [13]:
a = np.array([1, 2])
b = np.array([3, 4])

print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))


Vertical Stack:
 [[1 2]
 [3 4]]
Horizontal Stack:
 [1 2 3 4]


In [14]:
arr = np.array([10, 20, 30, 40, 50])
print("Greater than 30:", arr[arr > 30])


Greater than 30: [40 50]


In [15]:
##Useful NumPy Functions

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Mean:", np.mean(arr))
print("Std Dev:", np.std(arr))
print("Argmax:", np.argmax(arr))


Sum: 21
Max: 6
Mean: 3.5
Std Dev: 1.707825127659933
Argmax: 5


In [17]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

# Automatically expands shapes to match
print("Broadcasted Addition:\n", a + b)

Broadcasted Addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [18]:
mat = np.arange(1, 10).reshape(3, 3)
print("Matrix:\n", mat)
print("Diagonal Sum:", np.trace(mat))


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Sum: 15
